---
title: "PCA_practice"
author: "kimp"
date: "11/9/2017"
output: html_document
---

# Part III  
## Also in this repository is a data set and codebook from Rod Martin, Patricia Puhlik-Doris, Gwen Larsen, Jeanette Gray, Kelly Weir at the University of Western Ontario about people's sense of humor. Can you perform a PCA on this data?

```{r cars}
humor <- read.csv("humor_data.csv")
```

```{r}
humor <- scale(humor, center = TRUE)
```

```{r}
pca <- prcomp(humor, scale = TRUE)
```

```{r}
pca$sdev
pca$sdev^2
summary(pca)
plot(pca, type = "lines")
```

```{r}
D5 <- as.data.frame(pca$x)
COR3 <- cor(humor)
corrplot(COR3, order="AOE", method="circle", tl.pos="lt", type="upper",        
tl.col="black", tl.cex=0.6, tl.srt=45,  
        addCoef.col="black", addCoefasPercent = TRUE,
        sig.level=0.50, insig = "blank")

#0 coorelation?
```

```{r}
pca$rotation
loadings <- abs(pca$rotation)
sweep(loadings, 2, colSums(loadings))
biplot(pca)
```

```{r}
#scree plot of porportion of variance
```

```{r}
#scree plot for cumsum of porportion of variance?
```

